[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "2v9bXwSzT9tER9GEDF1uQCdEBecSs3xCtLpTmPLr4nY5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/u_cel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
